language: node_js
node_js:
  - '14.0'

jdk: openjdk16

sudo: required

services:
  - docker
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2

before_install:
  - chmod +x mvnw
  - jdk_switcher use openjdk16

script:
  - ./mvnw -Pprod clean package -DskipTests
  - java -Dserver.port=$PORT -jar target/crypto-tracker-0.0.1-SNAPSHOT.jar

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on: main
  app: troy-crypto-tracker
